baseURL = 'https://geene.io/'
languageCode = 'en-us'
title = 'GeeNe'
theme = 'mainroad'

[params]
  author = "elr0nda"
  description = "My Virtual Brain"
  readmore = true

#[Params.style.vars]
#  highlightColor = "#483888"

[params.logo]
  image = "img/logo.jpg"
  title = "GeeNe"
  subtitle = "The imaginary world where Geek and Nerd particles coexist"
  highlightColor = "#00FF00"
